---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    #DownloadPath: "/tmp/env/"
  roles:
  - { role: Download, ReqSetup=="Download" }
  - { role: CreateAzureInstance, ReqSetup=="AzureSetup" or when: ReqSetup=="CreateAzureInstance" }
 
#ansible-playbook main.yml -i environments/Azure -f 5 -e Environment=Azure -e ReqSetup=AzureSetup --user anirudh --become
#ansible-playbook main.yml -i environments/Azure -f 5 -e Environment=Azure -e ReqSetup=CreateAzureInstance
# 

- hosts: WebServers
  gather_facts: yes
  roles:
   - { role: Copy, when: ReqSetup=="Copy" }
   - { role: Tomcat, when: ReqSetup=="Tomcat" }
   - { role: AWS-copy, when: ReqSetup=="Deploy" }
   - { role: Docker, when: ReqSetup=="Docker" }
   - { role: Extra, when: ReqSetup=="Extra"}

#ansible-playbook main.yml -i environments/QA -f 5 -e Environment=QA -e ReqSetup=Docker --user ubuntu --become

- hosts: AzureVM
  gather_facts: no
  roles:
  - { role: Docker, when: ReqSetup=="AzureSetup" or ReqSetup=="Docker"}
  - { role: SetupWinnov, when: ReqSetup=="AzureSetup" or ReqSetup=="Winnov" }

#ansible-playbook main.yml -i environments/Azure -f 5 -e Environment=Azure -e ReqSetup=Docker --user anirudh --become 
#ansible-playbook main.yml -i environments/Azure -f 5 -e Environment=Azure -e ReqSetup=Winnov --user anirudh --become

