---
- name: Install Java 1.8
#  sudo: yes
  apt: name=openjdk-8-jdk

- name: add group "tomcat"
  group: name=tomcat

- name: add user "tomcat"
  user: name=tomcat group=tomcat home=/usr/share/tomcat
  become: True
  become_method: sudo

- name: Create systemd service script for Tomcat
  template: #use config files from templates dir
    src: "templates/tomcat.service"
    dest: "/etc/systemd/system/tomcat.service"
  notify: restart tomcat #handler will be executed after all plays done on the node

#- name: Create tomcat-users.xml
#  template:
#    src: templates/tomcat-users.xml
#    dest: "home/ubuntu/conf/tomcat-users.xml"
#  notify: restart tomcat

